function randomarrayidx(list) {
  return Math.round(Math.random() * (list.length - 1));
}

function randomarrayelem(list) {
  return list[randomarrayidx(list)];
}

function randomname(id, level) {
  var name = "AdamVille";
  if(level >= cities.length || cities[level].length === 0) {
    name = cities[0][Math.floor(Math.random() * (cities[0].length-1))];
  } else {
    name = cities[level][Math.floor(Math.random() * (cities[level].length-1))];
  }
  
  return name;
}

function randomperson(gender) {
  var male = gender;
  var first = randomarrayelem(peoplenames.first[male ? "male" : "female"]);
  var last = randomarrayelem(peoplenames.last);

  return first + " " + last;
}

var cities = [
	[ // Hamlets
		"Ackhampstead",
		"Addingrove",
		"Alscot",
		"Ascott",
		"Asheridge",
		"Askett",
		"Aston Mullins",
		"Baker's Wood",
		"Ballinger Bottom",
		"Ballinger",
		"Barley End",
		"Beacon Hill",
		"Beamond End",
		"Berghers Hill",
		"Bolter End",
		"Booker",
		"Botley",
		"Botolph Claydon",
		"Boycott",
		"Bradville",
		"Broughton Crossing",
		"Broughton",
		"Buckland Common",
		"Burcott",
		"Burston",
		"Butlers Cross",
		"Cadsden",
		"Caldecote",
		"Calvert",
		"Chackmore",
		"Chalfont Common",
		"Chalkshire",
		"Charndon",
		"Chivery",
		"Coldmoorholme",
		"Cooks Wharf",
		"Coombe",
		"Cores End",
		"Crafton",
		"Cryers Hill"
	], [ // Villages
		"Darite",
		"Davidstow",
		"Delabole",
		"Devoran",
		"Dimson",
		"Dobwalls",
		"Doublebois",
		"Downderry",
		"Drakewalls",
		"Drift",
		"Duloe",
		"Duporth",
		"Durgan",
		"Dutson"
	], [ // Towns
		"Hailsham",
		"Halesowen",
		"Halesworth",
		"Halifax",
		"Halstead",
		"Haltwhistle",
		"Redenhall with Harleston",
		"Harlow",
		"Harpenden",
		"Harrogate",
		"Harrow",
		"Hartland",
		"Hartlepool",
		"Harwich",
		"Harworth and Bircotes",
		"Haslemere",
		"Haslingden",
		"Hastings",
		"Hatfield",
		"Hatherleigh",
		"Havant",
		"Haverhill",
		"Haxby",
		"Hayle",
		"Haywards Heath",
		"Heanor and Loscoe",
		"Heathfield",
		"Hebden Royd",
		"Hedge End",
		"Hednesford",
		"Hedon",
		"Helmsley",
		"Helston",
		"Hemel Hempstead",
		"Hemsworth",
		"Hendon",
		"Henley-in-Arden",
		"Henley-on-Thames",
		"Hertford",
		"Hessle",
		"Hetton",
		"Hexham",
		"Heywood",
		"Higham Ferrers",
		"Highworth",
		"High Wycombe",
		"Hinckley",
		"Hingham",
		"Hitchin",
		"Hoddesdon",
		"Holbeach",
		"Holsworthy",
		"Holt",
		"Honiton",
		"Horley",
		"Horncastle",
		"Hornsea",
		"Hornsey",
		"Horsforth",
		"Horsham",
		"Horwich",
		"Houghton Regis",
		"Howden",
		"Huddersfield",
		"Hungerford",
		"Hunstanton",
		"Huntingdon",
		"Hyde",
		"Hythe"
	], [ // Cities
		"Bath",
		"Birmingham",
		"Bradford",
		"Brighton & Hove",
		"Bristol",
		"Cambridge",
		"Canterbury",
		"Carlisle",
		"Chelmsford",
		"Chester",
		"Chichester",
		"London",
		"Westminster",
		"Coventry",
		"Derby",
		"Durham",
		"Ely",
		"Exeter",
		"Gloucester",
		"Hereford",
		"Kingston upon Hull",
		"Lancaster",
		"Leeds",
		"Leicester",
		"Lichfield",
		"Lincoln",
		"Liverpool",
		"Manchester",
		"Newcastle upon Tyne",
		"Norwich",
		"Nottingham",
		"Oxford",
		"Peterborough",
		"Plymouth",
		"Portsmouth",
		"Preston",
		"Ripon",
		"Salford",
		"Salisbury",
		"Sheffield",
		"Southampton",
		"St Albans",
		"Stoke-on-Trent",
		"Sunderland",
		"Truro",
		"Wakefield",
		"Wells",
		"Winchester",
		"Wolverhampton",
		"Worcester",
		"York"
	], [ // Castles
		"Arundel",
		"Aydon",
		"Berkely",
		"Berkhamstead",
		"Bodiam",
		"Carisbrooke",
		"Conisbrough",
		"Corfe",
		"Dover",
		"Dunster",
		"Goodrich",
		"Howard",
		"Kenilworth",
		"Kirby",
		"Leeds",
		"Lewes",
		"Lincoln",
		"Northumberland",
		"Norwich",
		"Orford",
		"Portchester",
		"Pendennis",
		"Sizerg",
		"Scotney",
		"Skipton",
		"Thornbury",
		"Tower of London",
		"Warwick",
		"Windsor"
	], [	// Counties
		"Abbeville",
		"Aiken",
		"Allendale",
		"Anderson",
		"Bamberg",
		"Barnwell",
		"Beaufort",
		"Berkeley",
		"Calhoun",
		"Charleston",
		"Cherokee",
		"Chester",
		"Chesterfield",
		"Clarendon",
		"Colleton",
		"Darlington",
		"Dillon",
		"Dorchester",
		"Edgefield",
		"Fairfield",
		"Florence",
		"Georgetown",
		"Greenville",
		"Greenwood",
		"Hampton",
		"Horry",
		"Jasper",
		"Kershaw",
		"Lancaster",
		"Laurens",
		"Lee",
		"Lexington",
		"Marion",
		"Marlboro",
		"McCormick",
		"Newberry",
		"Oconee",
		"Orangeburg",
		"Pickens",
		"Richland",
		"Saluda",
		"Spartanburg",
		"Sumter",
		"Union",
		"Williamsburg"
	], [ // Duchies
		"Rothesay",
		"Albany",
		"Montrose",
		"Ross",
		"Orkney",
		"Lennox",
		"Kintyr",
		"Hamilton",
		"Buccleuch",
		"Lauderdale",
		"Rothes",
		"Gordon",
		"Queensberry",
		"Argyll",
		"Douglas",
		"Atholl",
		"Montrose",
		"Roxburghe",
		"Ormonde",
		"Leinster",
		"Munster",
		"Abercorn"
	], [ // Archduchy
		"Baden",
		"Hesse",
		"Luxembourg",
		"Mecklenburg",
		"Oldenburg",
		"Anhalt",
		"Brunswick",
		"Holstein",
		"Limburg",
		"Nassau",
		"Lippe",
		"Bremen",
		"Reuss",
		"Saxe-Weimar",
		"Alsace",
		"Lorraine"
	], [ // Kingdoms
		"Prussia",
		"Bavaria",
		"Saxony",
		"Wurttemburg",
		"Austria",
		"Hanover",
		"Bohemia"
	], [ // Empires
		"Macedonia",
		"Babylonia",
		"Persia",
		"Brittania",
		"Byzantium",
		"Delhi",
		"Lotharingia",
		"Golden Horde",
		"Harsha",
		"Ilkhanate",
		"Manchukuo"
	]
];

var peoplenames = {
  "first" : {
    "male": [
      "Adam",
      "Brent",
      "Michael",
      "Jim",
      "Steve",
      "Rudy",
      "Mitchell",
      "Ben",
      "Chris",
      "Tom"
    ],
    "female": [
      "Tracy",
      "Sarah",
      "Julie",
      "Kim",
      "Donna",
      "Michelle",
      "Leslie"
    ]
  },
  "last" : [
    "Knope",
    "Wyatt",
    "Trager",
    "Haverford",
    "Mitchell",
    "Hill",
    "Smith",
    "Jones",
    "Boyd",
  ]
};